### ISSUE TITLE
Mít možnost si jednotlivou kontrolu při zakládání/editování pojmenovat

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#1]
**rozšíření**

Ve formuláři, kde si zadávám novou kontrolu (např. `/dash-board/project/add-check/1?type=0`) nebo edituji již existující, tak kromě zadání URL mít zde políčko o na zadání názvu. Např. `kontrola dostupnosti hlavní stránky`.

Tenhle název pak zobrazovat na přehledu všech kontrol v záhlaví daného widgetu. Do budoucna  pak také na dashboardu, pokud by se daná kontrola objevila v chybě, tak v seznamu chyb.

![pridani noveho kontroly pecka monitoring 2016-11-28 09-17-37](https://cloud.githubusercontent.com/assets/7138039/20660800/aae51a8a-b54b-11e6-8096-437cfe14f7c6.png)

**Comment by MilanPala** [comment]
V masteru a NO. Vlastní název se nyní spojuje s obecným názvem kontroly. Vyzkoušej a dej vědět.

**Comment by petrzdansky** [comment]
V pořádku, děkuji. Úkol zavírám.
