### ISSUE TITLE
Přidání kontroly na počet prodejných produktů na celém e-shopu

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#10]

**Comment by tomasfoltyn** [comment]
Nachystaný pull-request

Externí skript počítá produkty z parametrickýho filtru

**Comment by petrzdansky** [comment]
@tomasfoltyn Tomáši, máš tam prosím nachystanou nějakou možnost definovat rozdíl, při kterém se to upozornění aktivuje. Např. pokud je o XX produktů menší než minulý den? JInak se samozřejmě ty počty mění směrem nahoru/dolů a je potřeba reagovta jen v případě nějakého velkého skoku

**Comment by tomasfoltyn** [comment]
Byla tam jenom kontrola minimálního počtu.
Přidal jsem tedy i kontrolu na rozdíl oproti minulému stavu.

**Comment by MilanPala** [comment]
Připraveno jako obecná kontrola na číslo.
