### ISSUE TITLE
U rabbit kontrol (počet zpráv + počet consumerů) mít možnost nastavit ignorování platnosti certifikátu

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#104]
U rabbit kontrol (počet zpráv + počet consumerů) mít možnost při jejich založení skrze checkbox nastavit ignorování platnosti certifikátu.

Aktuálně je tohle ingnorování nastaveno přímo v kódu u kontroly na počet zpráv https://github.com/peckadesign/Monitoring/blob/a79fe859e8e8b0cd18b675ba2abf9bcbe79bde2c/app/Check/Consumers/RabbitQueueCheck.php#L17-L19

U kontroly na počet consumerů tahle výjimka ale není a kontroly selhávají.

Po dohodě je řešení skrze checkbox lepší v tom, že si každý určí, zda tuto kontrolu chce nebo nechce objeví. V případě, kdy by měl na server nasazen platný certifikát, tak pak by mu to defaultní nastavení v kódu nedalo vědět, že mu certifikát vypršel.

**Comment by MilanPala** [comment]
V masteru.

**Comment by petrzdansky** [comment]
@MilanPala Milane, děkuji. Otestováno a funguje. Úkol zavírám.
