### ISSUE TITLE
Při založení nové kontroly je problém s formátem času

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#109]
Pokud se snažím založit novou kontrolu na `dostupnost URL` (https://monitoring.peckadesign.com/dash-board/project/add-check/{{project_id}}?type=0) tak bez vyplněného času pro vypnutí kontroly (ale stejné chování při vyplněné hodnotě např. 00:00 a 00:01) dojde k zobrazení této chyby. Samotná kontrola se ale na pozadí založí

   - exception zde 
[exception_monitoring.html.zip](https://github.com/peckadesign/Monitoring/files/2660558/exception_monitoring.html.zip)

<img width="1670" alt="pridani nove kontroly pecka monitoring 2018-12-09 14-10-38" src="https://user-images.githubusercontent.com/7138039/49697881-0ff67180-fbbd-11e8-8178-5a47176f068f.png">

**Comment by MilanPala** [comment]
Opraveno.

**Comment by petrzdansky** [comment]
@MilanPala Milane, v pořádku. Děkuji. Úkol zavírám.
