### ISSUE TITLE
Notice při editaci Rabbit kontroly

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#110]
@MilanPala Milane, pokud jdu editovat Rabbit kontrolu na počet zpráv, tak editaci při zobrazení i uložení formuláře zobrazuje tuhle Notice. Podíváš se na to prosím

![notice undefined offset 0 2019-01-14 08-41-56](https://user-images.githubusercontent.com/7138039/51100897-7b44ec00-17d8-11e9-8919-62e6723b76f3.png)

**Comment by MilanPala** [comment]
Chyba se mi neprojevuje.

**Comment by petrzdansky** [comment]
Tak po úpravě hesla mě už také ne, tak aktuálně zavírám.
