### ISSUE TITLE
Hlídání Xpath na URL

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#111]
Je potřeba udělat novou kontrolu, která bude hlídat XPAth na zadané URL. Např. výskyt produktboxů na kategorii nebo box s akčními produty na hlavní stránce.

cc @JakubRejnus

**Comment by MilanPala** [comment]
V masteru.

**Comment by petrzdansky** [comment]
@MilanPala Milane, dáš k tomu nějako `readme` jak kontrolu správně nastavit, prosím?
