### ISSUE TITLE
Zkontrolovat, zda všechny kontroly respektují nastavení pozastavení notifikací

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#112]
@MilanPala Milane, i když mám pro hlavní projekt (který slučuje více podprojektů) nastavené pozastavení notifikací 00:00 - 00:30, tak stejně kontrola na dostupnost proběhla a notifikovala do Slacku. Jak budeš mít prostor, tak se na to můžeš podívat, určitě to ale není vůbec asap úkol

![uprava projektu pecka monitoring 2019-01-21 14-31-47](https://user-images.githubusercontent.com/7138039/51477730-a2c42780-1d89-11e9-8617-1b5d0adc3fa8.png)

**Comment by MilanPala** [comment]
Funguje to, ale kontrolu máte nastavenou jako referenční. Není vhodné mít běžnou kontrolu jako referenční, ty se kontrolují neustále.

Jako referenční si nastavte kontrolu třeba nějakého zámku nebo údržby.

**Comment by petrzdansky** [comment]
Děkuji, vysvětlili jsme si důvod osobně. Úkol zavírám.
