### ISSUE TITLE
Přidat ajaxový reload na hlavní dashboard

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#12]
**rozšíření**

Prosím o přidání automatického reloadu (asi ajaxového) na hlavní stranu - dasboard tak, abych měl stálý real-time přehled nad statusem a nemusel jsem ručně provádět reload. Prosím podobně jako to má NewRelic.

**Comment by MilanPala** [comment]
Je tam udělaný reload na každých 20 sekund. Bylo by lepší pořešit přes websockety, zatím takto.

**Comment by petrzdansky** [comment]
Zatím myslím dostačující. Ale možná bych se přimluvil ještě za jednu věc:

- [ ] někde v zápatí vypsat čas posledního reloadu, aby bylo na první pohled jasné, že ten reload jede a že se někde nesekl - to bych poznal podle starého data.

**Comment by MilanPala** [comment]
Do zápatí by musel už asi kodér, přidal jsem do hlavičky včetně odkazu pro reload.

**Comment by petrzdansky** [comment]
@MilanPala Milane, zatím postačující. Kodérské pravy se budu snažit psát do kodérského úkolu https://github.com/peckadesign/Monitoring/issues/13
