### ISSUE TITLE
Kontrola - upozornění na termín

### ISSUE THREAD

**Issue by davidfoltyn** [peckadesign/Monitoring#123]
Při zadání kontroly `Upozornění na termín` se nedaří spustit samotnou kontrolu.

Spuštění končí chybou:
<img width="1012" alt="Snímek obrazovky 2019-03-31 v 10 08 34" src="https://user-images.githubusercontent.com/309238/55286570-af728680-539d-11e9-95fe-6520ef5c4226.png">

**Comment by MilanPala** [comment]
Pořešeno, smazal jsem ji.
