### ISSUE TITLE
Při přihlášeném uživateli bez admin práv dochází k chybě

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#128]
@MilanPala MIlane, pokud je přihlášený uživatel bez admin práv a jde na výpis kontrol jakéhokoli projektu, tak se mu zobrazí následující chyba. Podle mě to bude mít souvislost s posledníma upravama. Děkuji za opravu

<img width="1565" alt="obrazek" src="https://user-images.githubusercontent.com/7138039/55561400-5e8ec500-56f2-11e9-8eaf-7b1a97d124b2.png">

**Comment by MilanPala** [comment]
Opraveno.

**Comment by petrzdansky** [comment]
@MilanPala Milane, děkuji. Potvrzuji správné chování. Úkol zavírám.
