### ISSUE TITLE
Zapauzované kontroly

### ISSUE THREAD

**Issue by martenb** [peckadesign/Monitoring#130]
Nejsem si jist, jestli se jedná o bug, ale proč se publikují i zapauzované kontroly? Viz např.

https://github.com/peckadesign/Monitoring/blob/master/app/Check/Commands/Publish/AliveChecksCommand.php#L11

Neměla by všude přibýt podmínka
['paused' => FALSE]

**Comment by MilanPala** [comment]
Ony se pořád kontorlují, jen nezobrazují varování. Je to kvůli tomu, že kontrola nemá ještě žádný stav a vypisovala by chybu. Při pauze se kontrola provede, uloží si stav a potom si ji člověk odpauzuje. Nevygenerují se tak žádné falešné poplachy. Proto nová kontrola vzniká zapauzovaná.

Pauza se týká jen notifikací, možná by bylo lepší udělat lepší lang.

**Comment by martenb** [comment]
Ok, díky za info.
