### ISSUE TITLE
Nelze zadat více front z RabbitMQ (oddělené čárkou)

### ISSUE THREAD

**Issue by Qitek85** [peckadesign/Monitoring#134]
### Je třeba vyřešit
- nelze zadat více front oddělených čárkou pro monitoring

### Jak lze vyvolat popisované chování

1. na URL https://monitoring.peckadesign.com/dash-board/check/edit/392
2. přejdi do pole `Fronty`
3. zadej například `seoAliasUpdater.3,seoAliasUpdater.4`
4. po uložení nastane chyba

### Očekávané chování
- [ ] mělo by být možné zadat více front oddělených čárkou, prosím o fixaci

### Screen1
<img width="1830" alt="Úprava kontroly – Pecka Monitoring 2020-06-10 12-32-01" src="https://user-images.githubusercontent.com/34915615/84257950-6deb7880-ab16-11ea-94ff-7a4ed449a95a.png">

### Screen2
<img width="1924" alt="Hudy – Pecka Monitoring 2020-06-10 12-32-44" src="https://user-images.githubusercontent.com/34915615/84257989-7fcd1b80-ab16-11ea-9ac5-4a225441f33f.png">

**Comment by MilanPala** [comment]
Máš to špatně zadané, musíš si zadat ke každé frontě očekávaný počet, máš jen jeden.
