### ISSUE TITLE
Chyba při editaci záznamu kontroly počtu zpráv ve frontě

### ISSUE THREAD

**Issue by martinsifra** [peckadesign/Monitoring#142]
## Co nefunguje?
Dokud se u záznamu kontroly počtu zpráv nepodaří poprvé zjistit počet zpráv, nelze záznam editovat. Lehce se tak stane pokud zadáme například špatnou adresu nebo neplatné přihlašovací údaje.

![image](https://user-images.githubusercontent.com/1210906/104183189-de8ea680-5411-11eb-9d7f-c420cdf210d1.png)

**Comment by MilanPala** [comment]
Opraveno validací vstupu, aby se do chybného nastavení nebylo možné dostat.

![image](https://user-images.githubusercontent.com/1717814/106159501-25f09300-6185-11eb-9947-193b35b8d730.png)
