### ISSUE TITLE
Typed property Pd\Monitoring\DashBoard\Presenters\ProjectPresenter::$project must not be accessed before initialization search►

### ISSUE THREAD

**Issue by AloisJasa** [peckadesign/Monitoring#144]
- Při přidání podprojektu.
- Url `/dash-board/project/add?parent=58#`

Typed property Pd\Monitoring\DashBoard\Presenters\ProjectPresenter::$project must not be accessed before initialization search►

![Snímek obrazovky 2021-01-28 v 10 02 34](https://user-images.githubusercontent.com/17596051/106114541-f4110980-614f-11eb-9a07-287c27e74c41.png)

![Snímek obrazovky 2021-01-28 v 10 04 14](https://user-images.githubusercontent.com/17596051/106114733-30dd0080-6150-11eb-9f98-09746187b6c5.png)

(nepřidávám kompletní exceptionu s údaji o serveru)

**Comment by MilanPala** [comment]
Opraveno v masteru.

**Comment by AloisJasa** [comment]
Funguje. Díky moc 👍
