### ISSUE TITLE
Vytvoření klientského přístupu

### ISSUE THREAD

**Issue by michalmasek2** [peckadesign/Monitoring#147]
Pro potřeby klientů prosím o vytvoření nového typu účtu, který jim umožní:

- [x] přihlášení se do https://monitoring.peckadesign.com/ bez nutnosti mít GH účet 
- [x] přihlášení z externí IP (můžeme dodat seznam IP)
- [x] zobrazení jen vybraných projektů (klient uvidí jen svoje aktivní projekty a kontroly) 
- [x] zobrazení jen vybraných kontrol z projektu
- [x] odesílání notifikací do Slacku klienta
- [x] klient bude mít pouze read-only práva

Zobrazení vybraného projektu, nebo jen některých kontrol můžeme vyřešit i tím, že pro klienta založíme nový projekt a v něm nastavíme pouze relevantní kontroly. 

cc @tomasbukovsky

**Comment by MilanPala** [comment]
Je to celkem velká a komplexní úprava, respektive doplnění funkcí.

> přihlášení z externí IP (můžeme dodat seznam IP)

Jako že když si zadám do profilu IP adresu, tak se nebudu muset přihlašovat se jménem/heslem? Nebo kromě jména a hesla to bude vyžadovat ještě ověření IP adresy? První varianta mi přijde celkem nebezpečná, IP adresa nemusí být vždy tak úplně pevná, jak si člověk myslí.

> zobrazení jen vybraných kontrol z projektu

Šel bych cestou toho druhého projektu, minimálně ze začátku, ať to nenafukujeme.

----------------

Viděl bych to zhruba na týden práce.

**Comment by michalmasek2** [comment]
@MilanPala 

> přihlášení z externí IP (můžeme dodat seznam IP)

Myslel jsem, že monitoring je omezen na naši firemní IP/VPN, tak že by klient dodal jejich IP adresy, které bychom povolili. Jestli to neomezujeme, tak není potřeba.

**Comment by michalmasek2** [comment]
@MilanPala domluveno s @Qitek85, že zařadíme do výroby v posledním dubnovém týdnu.

**Comment by MilanPala** [comment]
Všechno připraveno. Nastavení probereme po Slacku.

**Comment by MilanPala** [comment]
@michalmasek2 Ještě tě k tomu něco napadá, nebo můžeme zavřít?

**Comment by michalmasek2** [comment]
@MilanPala všechno šlape, zavírám
