### ISSUE TITLE
Slack Integrace – přidat možnost editovat konkrétní kanál na Slacku

### ISSUE THREAD

**Issue by AloisJasa** [peckadesign/Monitoring#161]
### Aktuální stav
Aktuálně je název kanálu natvrdo `#monitoring`

### Motivace
Ne všechny kontroly je vhodné posílat do globálního kanálu #monitoring. Proto máme kontroly rozděleny na důležité (posílají se do globálního firemního `#monitoring`) a "Méně důležité alerty" (zatím sledujeme individuálně – ikona sluchátka).
Proto vznikl požadavek mít možnost zvolit/editovat konkrétní kanál – projektový monitoring.

### Zadání
- Rozšíření `Pd\Monitoring\Slack\Integration`
  - Mít možnost editovat název cílového kanálu
  - Defaultně nechat `#monitoring`
- `#monitoring` je natvrdo i pro reportování aktivace/deaktivace maintenance

**Comment by AloisJasa** [comment]
Na první pohled by se mělo jednat o místa:
- entita https://github.com/peckadesign/Monitoring/blob/master/app/Slack/Integration.php
- norifikace https://github.com/peckadesign/Monitoring/blob/master/app/Check/Commands/SlackCheckStatusesCommand.php#L204
- aktivace maintenance https://github.com/peckadesign/Monitoring/blob/master/app/DashBoard/Controls/Maintenance/Control.php#L92

**Comment by MilanPala** [comment]
Ještě je tu druhá možnost, jak konkrétní projekt notifikovat do jiného kanálu. Přidal bych volbu názvu kanálu do projektu `Pd\Monitoring\Project\Project` s tím, že bych dal i do té entity `Pd\Monitoring\Slack\Integration`, jak navrhuješ. V 

Pokud chci ovlivnit kanál pro celou integraci, tak to je jasná volba podle tvého návrhu. Když si chci nějaký projekt nechat posílat jinam, tak ještě volbu na úrovni projektu.

-------------

Pokud bys byl pro tvé řešení, tak je potřeba do názvu integrace v selectu na projektu (https://github.com/peckadesign/Monitoring/blob/master/app/DashBoard/Controls/SlackIntegrationOnProject/Factory.php#L39) doplnit do závorky ještě název kanálu, aby bylo jasné, jakou integraci vybírám. Třeba `PeckaDesign (#monitoring)`, `PeckaDesign (#monitoring-google)` apod.

**Comment by petrzdansky** [comment]
Podle mě jsou tu dvě úrovně:
- možnost nastavit jiný Slack kanál pro celý projekt když si to chceš přesměrovat vše
- to, na co míří ale podle mě Lojza je to, že máš na projektu např. 40 kontrol a z toho 30 je víceméně upozorňující na něco, co není kritické a stačí, když se o tom dozví tým daného projektu. Ale těch zbývajících 10 je kritických a chceš, aby chodili do toho obecného monitoring kanálu a dokázal zasáhnout v nejnutnějším případně např. někdo z jiného projektu

**Comment by MilanPala** [comment]
Potom je potřeba nastavit název kanálu až na úroveň entity Check. Je to potom kaskáda - globální kanál v Integration, projektový kanál v Project a kanál pro kontrolu v entitě Check.

Varianta s názvem kanálu v integraci je trochu nepříjemná, protože entita integrace nevstupuje do požadovaných metod, chodí tam vygenerovaná URL.

**Comment by AloisJasa** [comment]
> Varianta s názvem kanálu v integraci je trochu nepříjemná, protože entita integrace nevstupuje do požadovaných metod, chodí tam vygenerovaná URL.

Bude se muset upravit.


Když se nedávno přidaly integrace do slacku, tak mně dává největší smysl to přidat k nim. 
Tzn. NE do jednotlivých kontrol nebo k projektu.

### Umím si představit že potom podprojekty mají nastaveny integrace:

#### Podprojekt – méně důležité alerty
slack | kanal
--- | ---
PeckaDesign | #tym_monitoring


#### Podprojekt – hlavní kontroly
slack | kanal
--- | ---
PeckaDesign | __default__ (#monitoring)
Klient | __default__ (#monitoring)
PeckaDesign | #tym_monitoring 

(pozn.: ne všichni sledují firemní monitoring, proto ta rádoby duplicitní 2x Peckadesign)

**Comment by MilanPala** [comment]
Toto mě osobně nedává smysl, když mám jeden projekt. Raději bych měl jeden projekt a měnil si každou kontrolu zvlášť. Ale viděl jsem, že se to takto používá. Nicméně je to první půlka toho mého řešení, takže je možné to takto udělat.
