### ISSUE TITLE
U hodnoty `timeout` definovat jednotku

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#2]
**rozšíření**

Ve formuláři, kde si zadávám novou kontrolu (např. /dash-board/project/add-check/1?type=0) nebo edituji již existující prosím vedle labelu `timeout` definovat jednotku. Buď přímo za název do hranatých závorek, nebo jako placeholder do inputu před napsáním hodnoty. Primárně jsem pro tu první možnost a do inputu specifikovat text, že se jedná o hodnotu, kterou očekávám jako dobu odpovědi a ne čas, jak často se má systém na danou URL dotazovat.

**Comment by MilanPala** [comment]
Připraveno v PR #72. Čeká na review.

**Comment by MilanPala** [comment]
V masteru.
