### ISSUE TITLE
Pořadí výpisu sledovaných webů

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#23]
Prosím, zda by šly tyhle dvě věci (ideálně, kdyby obě fungovali funkcí drag&drop, která se dá vzít z košíku na korálcích):

- [x] individuálně pro každého uživatele mít možnost si změnit pořadí vypsaných sledovaných webů. Teď když chci sledovat Nay a Korálky, tak je mám pod přehybem a po každém reloadu se mi stránka posune nahoru

- [ ] na detailu webu si mít možnost seřadit sledované kontroly. Zde si myslím, že už to může být společné pro všechny uživatele

Nevím, co je potřebné nachystat od programátora (@milaPala ?) a co je už na kodérovi

**Comment by hhackerikCZ** [comment]
Připraveno v PR #36

**Comment by petrzdansky** [comment]
@MilanPala Milane, dělají se i pro Monitoring test servery?

**Comment by aloisjasa** [comment]
@petrzdansky kdyby ano, viděl bys v PR odkaz na sestavení a v případě úspěšného pak odkaz na konkrétní adresu na test serveru. Takže ne. A není ani třeba, doteď s tím pracovali jen programátoři, takže by to zbytečně zatěžovalo tetovací server.
Monitoring i CIServer se ladí lokálně ("po staru"). Spustíš si to třeba pres Vagrant na lokále a v PHPStormu (nebo CLI) si naladíš tu správnou větev, kterou chceš testovat.

**Comment by MilanPala** [comment]
Je to jak píše @aloisjasa. Ty projekty jsou trochu nestandardní oproti našim hlavním projektům a tak tyto funkce nemají. Až bude úkol hotový, dám ti vědět a zkusíš si ho u mě.

**Comment by petrzdansky** [comment]
Ok, o tom odkazu v PR samozřejmě vím a byla to první věc, kam jsem se šel podívat a až pak položil dotaz. Je to škoda, stejný příklad je pak i PeckaWeb (viz úkol https://github.com/peckadesign/PeckaDesign2015/issues/180#issuecomment-287334703).

Ale budiž :-)

**Comment by MilanPala** [comment]
NO.

**Comment by MilanPala** [comment]
> na detailu webu si mít možnost seřadit sledované kontroly

Nejsem si jistý, zda to je vhodné. Každý projekt by tak měl jiné pořadí. Takto je člověk zvyknutý, že první jsou alivechecky, potom https, pak feedy, potom rabiti. Ladil třeba pořadí typů kontrol, případně nějak formu, aby to vypadalo lépe.

**Comment by petrzdansky** [comment]
> Nejsem si jistý, zda to je vhodné. Každý projekt by tak měl jiné pořadí. Takto je člověk zvyknutý, že první jsou alivechecky, potom https, pak feedy, potom rabiti. Ladil třeba pořadí typů kontrol, případně nějak formu, aby to vypadalo lépe.

Pokud je to jednotné, tak je to ok. Nevím, jak to bylo v době zadání, ale připadlo mi, že se mi to řadilo v tom pořadí, v jaké jsem kontroly zakládal. Pokud ale máme stanovené pevné pořadí jednotlivých kontrol, tak je to nejideálnější

**Comment by petrzdansky** [comment]
> Nejsem si jistý, zda to je vhodné. Každý projekt by tak měl jiné pořadí. Takto je člověk zvyknutý, že první jsou alivechecky, potom https, pak feedy, potom rabiti. Ladil třeba pořadí typů kontrol, případně nějak formu, aby to vypadalo lépe.
> 
> Pokud je to jednotné, tak je to ok. Nevím, jak to bylo v době zadání, ale připadlo mi, že se mi to řadilo v tom pořadí, v jaké jsem kontroly zakládal. Pokud ale máme stanovené pevné pořadí jednotlivých kontrol, tak je to nejideálnější

Ověřeno a funguje to. Úkol zavírám a děkuji
