### ISSUE TITLE
Upravit chování odezvy url adresy

### ISSUE THREAD

**Issue by aloisjasa** [peckadesign/Monitoring#27]
Upravit kontrolu odezvy url adresy, pokud první ping selže, tak než se ta entita uloží, tak udělat ještě jednu kontrolu.
Občas může vyhnít na timeoutu třeba. Tak se to pro jistotu zopakuje.

**Comment by MilanPala** [comment]
Díky, v masteru. Uvidíme, jak se to osvědčí a případně upravíme.

**Comment by MilanPala** [comment]
Vyladění a funguje
