### ISSUE TITLE
Nápad: toggle na maintenance mode

### ISSUE THREAD

**Issue by fprochazka** [peckadesign/Monitoring#33]
* button na "toggle" maintenance módu pro celý jeden projekt
* měl by vypnout "spamování" na slack a poslat jednu notifikaci "tenhle uživatel dělá maintenance"
* nástroj půjde stále využít na kontrolu že maintenance probíhá dle očekávání, ale nebude to spamovat slack
* následně možnost přepnout se zpátky do normálu

**Comment by MilanPala** [comment]
NO.

**Comment by Mikulas** [comment]
Tohle vypadá, že je na masteru vyřešené?

**Comment by MilanPala** [comment]
Ano.
