### ISSUE TITLE
Vlastní user agent

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#37]
Aby se provoz z Monitoringu dal sledovat, navrhuji udělat vlastní user agent pro všechny requesty. Něco ve stylu `PeckaMonitoringBot/1.0`.

**Comment by landsman** [comment]
Mohu se zeptat, jak to pak filtrujete v GA?
Takto?
![image](https://user-images.githubusercontent.com/3184228/28776054-2a369e34-75f5-11e7-9fbd-d05d5edab475.jpg)

**Comment by MilanPala** [comment]
My to používáme pro sledování v access logu, do GA jsem to ještě nenastavoval.

**Comment by landsman** [comment]
Tak zvyšuje to přístupy, zkresluje data, pokud to pinguje 1x za minutu.

**Comment by MilanPala** [comment]
Chodí nám to z interní IP adresy, kterou máme prý vyloučenou.

**Comment by landsman** [comment]
Aha, takže vyloučit IP adresu by šlo, pravda!
