### ISSUE TITLE
Tlačítka projektu do záhlaví

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#42]
Tlačítka na stránce projektu jsou v patičce a nejsou tak po ruce. Navíc se rozbalovací menu rozbalí pod konec stránky.

![megapixel pecka monitoring 2017-03-27 12-10-47](https://cloud.githubusercontent.com/assets/1717814/24351564/7c6f3570-12e6-11e7-8b5d-522dff8a2502.png)

Prosím tedy o přesunutí tlačítek někam do záhlaví. Vedle nadpisu je celkem hodně místa.

![megapixel pecka monitoring 2017-03-27 12-11-36](https://cloud.githubusercontent.com/assets/1717814/24351630/c715079e-12e6-11e7-8e92-f6e5c22600f3.png)

Pro ilustraci přikládám printscreen z Testomata, kde mají takovou +- standardní adminovskou šablonu.

![testomato megapixel cz project](https://cloud.githubusercontent.com/assets/1717814/24351694/094121c0-12e7-11e7-8826-7860e4eed557.png)

Statická šablona se všemi CSS je připravená v souboru `www/html/project.html`.

**Comment by kristynam** [comment]
Prosím o kontrolu

**Comment by MilanPala** [comment]
Je to super, díky moc.

**Comment by MilanPala** [comment]
NO.

**Comment by petrzdansky** [comment]
Dobrá práce @MilanPala a @kristynam!
