### ISSUE TITLE
Problém s mazáním kontroly dostupnosti URL

### ISSUE THREAD

**Issue by mhudakcz** [peckadesign/Monitoring#47]
Pokud se pokouším smazat jednu z monitorovaných URL tak to padne na chybu - viz. screen.

![1fed83ba-1f75-11e7-90c2-6a5ca86d0871](https://cloud.githubusercontent.com/assets/1717814/24953229/d22aa9fe-1f7a-11e7-9925-9977a7ba92d3.png)

**Comment by MilanPala** [comment]
Opraveno, NO.

**Comment by MilanPala** [comment]
Aha, asi není, beru zpět.

**Comment by MilanPala** [comment]
Opravneo, NO.

**Comment by mhudakcz** [comment]
OK, otestováno. 
Děkuji a zavírám.
