### ISSUE TITLE
Přidání kontroly na existenci feedu

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#5]
Nastavení:
 - Adresa feedu
 - Název feedu

Výsledek:
 - stav

Ještě by bylo potřeba pořešit, že feed obsahuje data. Např. přes XPath nebo tak.

**Comment by tomasfoltyn** [comment]
Nestačilo by na kontrolu dat jenom vědět velikost? Ať se nemusí ty feedy stahovat.

**Comment by tomasfoltyn** [comment]
Nachystaný pull-request.

Kontroluje se velikost a stáří feedu.

**Comment by MilanPala** [comment]
Super, díky.
