### ISSUE TITLE
Jak nastavit supervisor?

### ISSUE THREAD

**Issue by landsman** [peckadesign/Monitoring#57]
Ahoj,
mohli by jste mě prosím navést, jak správně nastavit supervisor, aby četl [supervisor.conf](https://github.com/peckadesign/Monitoring/blob/master/config/supervisor.conf) z appky, dynamicky? Dělám to poprvé a googlím o 106. 

děkuji

**Comment by MilanPala** [comment]
Vyřešeno po Slacku. Buď symlink, nebo překopírovat do /etc/supervisor/conf.d/

**Comment by landsman** [comment]
Doplním ještě nějaký návod v PR.
