### ISSUE TITLE
Kontrola https certifikatu

### ISSUE THREAD

**Issue by landsman** [peckadesign/Monitoring#59]
Upravit v administraci validaci domény tak, aby šla zadat bez protokolu, nebo ji očišťovat zde: https://github.com/peckadesign/Monitoring/blob/master/app/Check/Consumers/CertificateCheck.php#L34

**Comment by MilanPala** [comment]
Také by bylo hezké mít v inputu placeholder.

**Comment by MilanPala** [comment]
V masteru.
