### ISSUE TITLE
Přidání kontroly na minimální počet consumerů fronty

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#6]
Nastavení:
 - adresa pro API RabbitMQ
 - minimální požadovaný počet

Výsledek:
 - stav
 - počet consumerů

**Comment by tomasfoltyn** [comment]
Nachystán pullrequest

**Comment by MilanPala** [comment]
V masteru. Díky

**Comment by MilanPala** [comment]
Když vypadne tato kontrola, tak bude check svítit stále zeleně, protože se nekontroluje aktuální stav, že to nejede. Je potřeba doplnit o kontrolu, zda poslední kontrola proběhla před nějakou dobou, třeba hodinou.

**Comment by tomasfoltyn** [comment]
Tahle kontrola by mohla být všude.
