### ISSUE TITLE
Přidání kontroly na HTTP stavový kód

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#7]
Nastavení:
 - adresa
 - požadovaný stavový kód

Výsledek
 - Stav
 - Stavový kód

Vhodné např. pro kontrolu na 403 atd.

**Comment by tomasfoltyn** [comment]
Nachystán pull-request

**Comment by landsman** [comment]
Tohle je nachystane jako samostatna kontrola? Docela by se mi to libilo pouze jako checkbox do stavajici kontroly "Dostupnost URL".

**Comment by MilanPala** [comment]
@landsman Co by ten checkbox znamenal, jaký by měl účel? "Dostupnost URL" hlídá stav 200. Neumí nic jiného, na to byla právě myšlená tato kontrola (např. na redirecty z ne-www domén atd.). Budou to tedy zřejmě jiné URL, než ty pro "Dostupnost URL".

**Comment by MilanPala** [comment]
V masteru.
