### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by landsman** [peckadesign/Monitoring#71]
Neuvažovali jste o použítí aplikace v rámci docker containeru?
Říkám si, že by mohlo odpadnout prvotní nastavování, propojování services.

**Comment by MilanPala** [comment]
Uvažovali na PoSobotě. Je potřeba Docker nastavit tak, aby byl možný snadný upgrade v případě vydání nové verze, abys nepřišel o data.

Můžeš připravit PR. Díky

**Comment by landsman** [comment]
Myslíš mysql?

Dne 8. 8. 2017 8:16 napsal uživatel "Milan Pála" <notifications@github.com>:

Uvažovali na PoSobotě. Je potřeba Docker nastavit tak, aby byl možný snadný
upgrade v případě vydání nové verze, abys nepřišel o data.

Můžeš připravit PR. Díky

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/peckadesign/Monitoring/issues/71#issuecomment-320861051>,
or mute the thread

**Comment by MilanPala** [comment]
No všechno, co ukládá data. Hlavně MySQL, ale případně i další věci. Ačkoliv o frontu RabbitMQ můžeš přijít. Výhledově by to byly další databáze, kam by se ukládala historická data. Sám s Dockerem neumím, takže víc neporadím.

**Comment by landsman** [comment]
Uměl by nám poradit @iBobik ? :-)

**Comment by f3l1x** [comment]
Rad vam s tim pomuzu ;-) @landsman @MilanPala

**Comment by mstefan21** [comment]
docekr je fajn, delame s nim v praci, neni pripaden taky problem pomoct

**Comment by f3l1x** [comment]
Muzete sepsat zakladni pozadavky co to ma umet/mit? Jak si to tak predstavujete apod? :-) Priznam se, ze tenhle balicek nepouzivam, ale pokud to dame do dockeru, tak rad vyzkousim.

**Comment by iBobik** [comment]
Chystám na tohle téma kurz, zapište se :-)
https://www.naucmese.cz/kurz/zacni-s-dockerem-postav-si-lokalni-prostredi-pro-svuj-projekt

**Comment by landsman** [comment]
@f3l1x Rád bych především zjednodušil první nasazení, rozběhnutí pro lidi, co to nikdy nepoužili a třeba i neumí úplně s rabbitem. Automatizovat minimálně instalaci LAMP, Rabbita, třeba přihodit i Let's Encrypt a v command line po nich chtít například vyplnit základní údaje, které se promítnou do samotné instalace. Nevím, co všechno je dobře možné, s Dockerem nemám příliš zkušeností.

**Comment by landsman** [comment]
@f3l1x bylo by skvělé, kdyby to byl nějaký "samoinstalační" proces, 
kdy se do konzole promítnou nějaké dotazy, které musí člověk vyplnit.

**1. Technologie a aplikace pro docker file:**
1. Apache 2.4.x/Nginx
2. PHP 7.1.x
3. MariaDB/Mysql
4. RabbitMQ
5. supervisord
6. Let's encrypt (?)
7. myphpadmin / adminer

**2. Člověka bych nechal vypňovat:**
1.  [URL virtuálu](https://github.com/peckadesign/Monitoring/blob/master/config/config.local.example.neon#L25)
2. [Github appId](https://github.com/peckadesign/Monitoring/blob/master/config/config.local.example.neon#L2)
3. [Github Team ID](https://github.com/peckadesign/Monitoring/blob/master/config/config.local.example.neon#L29)
4. [Slack hook URL](https://github.com/peckadesign/Monitoring/blob/master/config/config.local.example.neon#L32)

**3. Automatizace:**
1. instalace: apache/nginx (http2, mod_rewrite), mysql, rabbit, supervisor
2. config.neon - připojení k db, rabbitovi.
3. nastavení supervisord, tj zkopírování obsahu souboru [supervisor.conf](https://github.com/peckadesign/Monitoring/blob/master/config/supervisor.conf) do: `/etc/supervisor/supervisord.conf` ... kdy smažeme:
```
[supervisord]
user=vagrant
directory=/vagrant
```
a změníme cestu k virtuálu: `www/index.php` na požadovaný tvar, co bude v dockeru.
4. nastavení crontab (zase s cestou k virtualu):
```
# Monitoring
*/1 * * * *        php /var/www/Monitoring/www/index.php pd:monitoring:check:publish:alive-checks
0,15,30,45 * * * * php /var/www/Monitoring/www/index.php pd:monitoring:check:publish:dns-checks
0 */6 * * *        php /var/www/Monitoring/www/index.php pd:monitoring:check:publish:certificate-checks
0,30 * * * *       php /var/www/Monitoring/www/index.php pd:monitoring:check:publish:feed-checks
0,15,30,45 * * * * php /var/www/Monitoring/www/index.php pd:monitoring:check:publish:rabbit-consumer-checks
*/1 * * * *        php /var/www/Monitoring/www/index.php pd:monitoring:check:slack-check-statuses
```
5. let's encrypt certifikát + renew job do crontab
6. poslat emailem / vytisknout do console nastavené URL k virtualu, myphpadmin / adminer, rabbit, supervisor, pro ruční administraci.
7. nastavit rutinu spouštění aplikací po restartu VPS (výpadek, ...), aby se nestalo že monitoring po výpadku VPS se sám nenastartuje (teď jsem někde řešil, fakt otrava :-) )

Napadá tě ještě něco @MilanPala?

**Comment by f3l1x** [comment]
@landsman Na NetteCampu se na to podivam.

**Comment by newPOPE** [comment]
Je tam toho dost :). Ako som uz spominal osobne by som to namotoval do jedneho image-u (nginx, fpm, supervisor, lets encrypt robot, adminer) a vyuzil services na rozdelenie do kontainerov. mysql a rabbit by som nechal na ofiko images.

Spustenie danych veci by uz potom mohlo byt samostatne napr:

- docker-compose up app (apache/nginx) (nastaruje http server + fpm)
- docker-compose up supervisord (nastartuje supervisor proc)
- docker-compose up cron (nastartuje cron daemon)

Kludne pomozem (ked @f3l1x nieco nastreli) len dajte mention.

**Comment by MilanPala** [comment]
Za mě je zásadní splnit správné verze a všechny požadavky na služby, ty myslím @landsman vyjmenoval všechny. Ještě composer chybí.

Supervisoru jde nastavit globální prefix cesty, takže úlohy mohou být spouštěny s relativní cestou. V soupisu úloh bych nechal ty relativní cesty a nalinkoval soubor do `/etc/supervisor/conf.d/monitoring.conf` a úpravou globální konfigurace v `/etc/supervisor/supervisord.conf` bych rozlišoval prefixy cest podle prostředí. Zůstane tak univerzální předpis pro Vagrant, Docker a případně další.

Adminer má vlastní image, pokud se nepletu. Kdyby to zjednodušilo jeho aktualizovatelnost, bude to super.

Jinak soubory DB a aplikace potřebujeme mít mimo Docker, zbytek nemá perzistentní data.

**Comment by iBobik** [comment]
Doporučuji se vyhnout použití supervizoru uvnitř kontejneru, protože to pak může způsobovat různé problémy při orchestraci. Best practice je jedna sluzba - jeden kontejner. 

S tím, že třeba monitoring a https endpoint bývá řešen mimo stack projektu, obvykle v orchestraci. To jsou zároveň ty věci, které nepotřebujete na lokále.

Jan Pobořil
http://honza.poboril.cz/

15. 8. 2017 v 7:59, Milan Pála <notifications@github.com>:

**Comment by newPOPE** [comment]
@iBobik s tym, ze jeden kontainer = jedna sluzba uplne suhlasim. Mne ide skor o to, ze pokial chces mat napr. cron alebo supervisor tak tam bohuzial potrebujes aj zdrojaky tak mi pride vyhodnejsie to mat v jednom image. Lenze image != kontainer tak ako trieda != objekt. To co som navrhol pouzivam (len s cron-om) a nie je s tym ziadny problem resp. doteraz (cca 2 roky) nebol. 

Inspiracia bola zo sentry https://hub.docker.com/_/sentry/. Presnejsie bod 6.

**Comment by landsman** [comment]
Jak by se v tom kontejneru řešili případné updaty? Resp. dalo by se to také zautomatizovat nebo by to mělo mít obsluhu? Teď myslím composer update, spuštění db migrací.

**Comment by newPOPE** [comment]
@landsman dobra otazka. Moznosti je opat viacero a treba si vybrat.

1. vzdy ked sa nieco updatne tak sa zostavi novy image vid https://hub.docker.com/_/php/ proste si vyberies image ktory chces (tu by ale update bol po kazdej zmene nginxu, zdrojakov,... aj ked predpokladam, ze taky nginx atd sa tak casto updatovat nebudu)
2. vyrobil by sa len tzv. runtime kontainer ktory bude obsahovat vsetko co je potrebne pre beh (nginx, composer, ...) no zdrojaky sa proste natiahnu pri starte kontainera (tak to riesi napr. drupal/wp images see https://github.com/docker-library/drupal/blob/9f8ce73be0a63586b26b6467310fb572be8209d2/8.3/apache/Dockerfile#L42)

Z mojich poznatkov sa moznost 2. hodi na vyvoj, moznost 1. je lepsia na produkciu.

**Comment by iBobik** [comment]
Jde to zkombinovat tak, aby se oba přístupy daly z jednoho image.

Jinak cron jsem obvykle dělal tak, že nějaký obecný cron image volá php kontejner přes síť (curl http nebo fastcgi), takže cron kontejner nepotřebuje obsahovat aplikaci. Taky to správně funguje při horizontálním škálování.

Jan Pobořil
http://honza.poboril.cz/

15. 8. 2017 v 10:47, Adam Stipak <notifications@github.com>:

**Comment by landsman** [comment]
@f3l1x podarilo se vam k tomu na nettecampu dostat? :)

**Comment by landsman** [comment]
Hola, měl by na tohle někdo čas rozpohybovat?
Rád jakkoliv pomohu.

**Comment by newPOPE** [comment]
@landsman ahoj, kedze sa toho nikto nechytil tak mozem sa vam na to pozriet v priebehu tohto tyzdna. Dam echo. Pripadne ta pingnem na slacku pehapkari?.

**Comment by landsman** [comment]
To by bylo super! Diky.

Dne 29. 10. 2017 20:07 napsal uživatel "Adam Stipak" <
notifications@github.com>:

**Comment by newPOPE** [comment]
Vieme prerobit konfiguraciu tak aby to tahalo z ENV premennych? Skusal som rozne postupy pomocou baliku https://github.com/wodCZ/nette-dotenv pripadne neon zapisu `::getenv(GITHUB_APPID)`. Problem je ze Kdyby/Github validuje dane konfiguracie https://github.com/Kdyby/Github/blob/master/src/Kdyby/Github/DI/GithubExtension.php#L52 lenze v tom case je v `$config['appId'] len `Nette\DI\Statement` cize nie string. Popravde si myslim, ze to vyzera na "bug" Nette\DI.

Nejake napady?

**Comment by newPOPE** [comment]
Tu je nastrel ako by to mohlo fungovat https://github.com/newPOPE/Monitoring/blob/development-in-docker/README.md#vývoj-v-docker-u hodil by sa niekto kto to realne pouziva resp. s kym by som mohol testovat (ja mam OSX kde su trochu ine poziadavky napr. na nastavenie mysql vid https://github.com/newPOPE/Monitoring/blob/development-in-docker/.docker/mysql/my.cnf kedy nefunguje aio)

Ak je niekto napiste na pehapkari @new_pope

**Comment by landsman** [comment]
Díky moc @newPOPE. Zítra se to chystám otestovat na Mac OS, Ubuntu a na Debian serveru. Chybí tam něco z tvého pohledu pro produkční používání?

**Comment by newPOPE** [comment]
@landsman treba doladiť konfigurácie a dev, prod mode.

**Comment by VeeeneX** [comment]
@newPOPE @landsman Staci uz len vytvoriť PR, nie?

**Comment by newPOPE** [comment]
Za mňa to zrejme nik iný netestol tak neviem

**Comment by MilanPala** [comment]
V masteru je návod, jak jedním příkazem spustit celý Monitoring přes připravený docker-compose. Zároveň se sestavuje image pro vlastní způsob běhu.

Považuji za vyřešené.
