### ISSUE TITLE
Kontrola na počet zpráv ve frontě

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#78]
Je potřeba dodělat novou kontrolu, která bude hlídat i počet zpráv ve frontě. Vhodné to je na fronty, kde by neměly být žádné zprávy nikdy, typicky DLX fronty.

**Comment by MilanPala** [comment]
V masteru. Jednodušší zadávání front řeší #82.

**Comment by petrzdansky** [comment]
@MilanPala Milane, super. Nastaveno a vše běží krásně.
