### ISSUE TITLE
Kontrola na libovolný DNS záznam

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#86]
Nyní kontrolujeme A záznam v rámci kontroly "Nastavení DNS". Bylo by lepší kontrolu převést na A záznam a rozšířit na možnost dalších typů záznamů (MX, TXT atd.)

**Comment by MilanPala** [comment]
V masteru.

**Comment by petrzdansky** [comment]
@MilanPala Milane, pro kontrolu TXT záznamu založíme jiný úkol?

**Comment by MilanPala** [comment]
Chtěl jsem nejdříve vyřešit SPF záznamy, aby nebylo potřeba po přidání TXT záznamů přepisovat staré. Ale mám namyšlenou komplikovanou kontrolu, takže ty asi dořeším někdy jindy.

TXT záznamy jsem doplnil.
