### ISSUE TITLE
Do hlídání `počtu zpráv v Rabbit frontě` mít možnot dát prolink na detail fronty v rabbit administraci

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#88]
Do hlídání `počtu zpráv v Rabbit frontě` mít možnot dát prolink na detail fronty v rabbit administraci. Např. https://ip_adresa:port/#/queues/%2F/nazev_fronty.

Při notifikaci do Slacku by se pak tahle URL vložila a dalo by se tak prokliknout přímo do té Rabbit administrace na detail fronty a začít to řešit.

**Comment by MilanPala** [comment]
V masteru. Je potřeba si do kontroly zadat odkaz na administraci.

**Comment by petrzdansky** [comment]
@MilanPala MIlane, děkuji. Úkol zavírám.
