### ISSUE TITLE
Chyba při editaci kontroly, která ještě nemá načtené údaje

### ISSUE THREAD

**Issue by petrzdansky** [peckadesign/Monitoring#89]
Pokud založím novou kontrolu, uložím formulář a pak u té kontroly kliknu na edit dříve než si u té kontroly načtu údaje samotnou kontrolou, tak editaci zobrazuje tuhle chybu:

![koralky pecka monitoring 2018-02-26 08-56-26](https://user-images.githubusercontent.com/7138039/36658933-fdc57086-1ad2-11e8-9198-a3e372f7e62b.png)

![uprava kontroly pecka monitoring 2018-02-26 08-54-15](https://user-images.githubusercontent.com/7138039/36658907-e1de7eda-1ad2-11e8-8d29-14cf0e5fa81a.png)

**Comment by MilanPala** [comment]
Opraveno, v masteru.

**Comment by petrzdansky** [comment]
Rychlejší než blesk :zap:. Děkuji moc :+1:
