### ISSUE TITLE
Podprojekty

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#94]
Projekty by mělo být možné hierarchizovat do jedné úrovně.

**Comment by MilanPala** [comment]
NO.

**Comment by petrzdansky** [comment]
@MilanPala Milane, děkuji za úpravu. Jejím zavedením se tam ale dostalo několik chyb:

**Comment by petrzdansky** [comment]
@MilanPala Milane, do komentáře https://github.com/peckadesign/Monitoring/issues/94#issuecomment-394278322 jsem doplnil jedno chybné chování. Prosím o opravu.

Úpravy z komentáře https://github.com/peckadesign/Monitoring/issues/94#issuecomment-396890485 zkontroluji brzy

> pokud jsem na projektu s více podprojektama, tak pokud jdu na podprojekt který je druhý v pořadí a dále, tak se mi klikáním na podzáložky jednotlivých kontrol nemění jejich obsah

**Comment by petrzdansky** [comment]
> v editaci kontroly identifikovat pod kterým podprojektem je zařazená a mít možnost to změnit

- select sice v editaci je, ale pokud vyberu jiný projekt než ve kterém aktuálně je a dám uložit, tak se kontrola nepřepáruje. Konkrétně jsem to zkoušel u kontroly https://monitoring.peckadesign.com/dash-board/project/edit-check/14?checkId=291 a zkoušel jsem ji přeřadit pod projekt `dobeado.co.uk` - project-36

**Comment by MilanPala** [comment]
Opraveno v masteru.

**Comment by petrzdansky** [comment]
@MilanPala Milane, zkontrolováno a funguje. Děkuji.
