### ISSUE TITLE
Kontrola na číselnou hodnotu

### ISSUE THREAD

**Issue by MilanPala** [peckadesign/Monitoring#99]
Kontrola si přečte ze zadné URL číselnou hodnotu a porovná podle nastavené očekávané hodnoty.

**Comment by MilanPala** [comment]
V masteru.

**Comment by petrzdansky** [comment]
@MilanPala Milane, je možné, že kontrola v případě kdy URL vrátí hodnotu 0, tak tu nulu nenačte do hodnoty `Zjištěná hodnota`? Teď se mi to tak chová na projektu a přemýšlím, zda by nebylo fajn, aby se i v monitoringu zobrazovala 0

**Comment by petrzdansky** [comment]
@MilanPala Milanem, super. Děkuji moc.
